# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_initial_userprofiles(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        UserProfile = apps.get_model("accounts", "UserProfile")
        for user in User.objects.all():
            UserProfile.objects.create(user=user)

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_anonymously', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_initial_userprofiles),
    ]
