# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:39
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160514_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='provider',
            field=models.CharField(choices=[('perdiem', 'Custom'), ('google-oauth2', 'Google'), ('facebook', 'Facebook')], max_length=15),
        ),
        migrations.AlterField(
            model_name='useravatarimage',
            name='img',
            field=models.ImageField(upload_to=accounts.models.user_avatar_filename),
        ),
    ]
